<a href="https://colab.research.google.com/github/LiscaAngriani/APM_Kelompok3/blob/main/Proyek_APM_NaiveBayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [49]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

In [50]:
#membaca data
data = pd.read_csv('nilai_to.csv')
X = data.iloc[:, [18,19]].values
y = data.iloc[:, 19].values

data.head()

Ranking          Nis                    Nama        Sekolah  \
0        1  20307332037      Rizqi Zuhdi Amarta  SMAN 1 PADANG   
1        2  20307331061  Resti Natalia Chaniago  SMAN 5 PADANG   
2        3  20307331062        Indah Widia Sari  SMAN 5 PADANG   
3        4  20307332049                 Mulyadi   MAN 2 PADANG   
4        5  20307331058          Elfaiza Warsya   SMA DONBOSCO   

                  Nama PTN                            Jurusan      PG  \
0   UNIVERSITAS GAJAH MADA  BANGUNAN SOSIAL DAN KESEJAHTERAAN  653.11   
1  UNIVERSITAS GADJAH MADA                            SEJARAH  484.58   
2    UNIVERSITAS INDONESIA                     SASTRA INGGRIS  481.70   
3    UNIVERSITAS INDONESIA                   SASTRA INDONESIA  465.99   
4    UNIVERSITAS INDONESIA           ILMU ADMINISTRASI NEGARA  485.77   

   Penalaran Umum  Pemahaman bacaan & menulis  Pengetahuan Umum  \
0             476                         476               598   
1             525                         525               595   
2             525                         525               560   
3             525                         525               560   
4             560                         560               490   

   Pengetahuan Kuantitatif  Inggris  Ekonomi  Sosiologi  Sejarah  Geografi  \
0                      658      672      621        622      559       642   
1                      595      574      560        560      560       595   
2                      560      560      560        525      595       560   
3                      525      543      560        525      560       525   
4                      560      546      525        595      490       490   

   Nilai TPS  Nilai TKS  Skor UTBK  Status Kelulusan  
0     622.76     610.85     617.47                 0  
1     568.75     569.80     569.28                 1  
2     560.00     560.00     560.00                 1  
3     542.50     542.50     542.50                 1  
4     551.25     529.20     540.23                 1

In [51]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [53]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [54]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [55]:
y_pred  =  classifier.predict(X_test)

In [56]:
y_pred

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0])

In [57]:
y_test

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0])

In [58]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test,y_pred)

print (cm)
print (ac)

[[11  0]
 [ 0  4]]
1.0
